import type { Metadata } from "next";
import localFont from "next/font/local";
import { Navbar } from "@/components";
import "../styles/globals.scss";

const regular = localFont({
  src: "./fonts/SF-Pro-Display-Regular.ttf",
  variable: "--regular-font"
})

const medium = localFont({
  src: "./fonts/SF-Pro-Display-Medium.ttf",
  variable: "--medium-font"
})

const semibold = localFont({
  src: "./fonts/SF-Pro-Display-Semibold.ttf",
  variable: "--semibold-font"
})

const heavy = localFont({
  src: "./fonts/SF-Pro-Display-Heavy.ttf",
  variable: "--heavy-font"
})

const script = localFont({
  src: "./fonts/VT323-.ttf",
  variable: "--heavy-font"
})

export const metadata: Metadata = {
  title: "Innovation Lab for Infrastructure Development",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${regular.variable} ${medium.variable} ${semibold.variable} ${heavy.variable}`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
